### ISSUE TITLE
[Style] getCurrentChannelInfo does not follow style of other methods

### ISSUE THREAD

**Issue by aaron-goff** [rokudev/automated-channel-testing#1]
In `RobotLibrary/Library/RobotLibrary.py`, the function `getCurrentChannelInfo()` currently loads the json response into the variable `res` at line 138. At line 139, the value of `res`'s key "value" (`res['value']` is stored in the `channel` variable. At line 140, `channel` is returned. This does not follow the same style as other functions in the same file, where they instead just return the value without first storing it in a variable. 

See `getDeviceInfo()` or `getElement()`

Proposed solution (starting at line 134):
```
    @keyword("Get current channel info")
    def getCurrentChannelInfo(self):
        app_response = self._client.get_current_app()
        self._checkResponse(app_response)
        res = json.loads(app_response.text)
        return res['value']
```

**Comment by rburdick100** [comment]
We've updated this and will have the fix in the next release.
