### ISSUE TITLE
Input information is incorrect in JavaScript Library docs

### ISSUE THREAD

**Issue by aaron-goff** [rokudev/automated-channel-testing#12]
[The documentation for `input`](https://developer.roku.com/en-ca/docs/developer-program/dev-tools/automated-channel-testing/javascript-library.md#inputdeeplinkingdata) uses the `launch` command.

[The documentation for getElements](https://developer.roku.com/en-ca/docs/developer-program/dev-tools/automated-channel-testing/javascript-library.md#getelements) is missing an example.

[The documentation for getFocusedElement](https://developer.roku.com/en-ca/docs/developer-program/dev-tools/automated-channel-testing/javascript-library.md#getfocusedelement) is missing an example.

[The documentation for getDevinceInfo](https://developer.roku.com/en-ca/docs/developer-program/dev-tools/automated-channel-testing/javascript-library.md#getdeviceinfo) is missing an example.

**Comment by jduval23** [comment]
Doc has been updated. Thanks for the input.
