### ISSUE TITLE
Getting response value empty when hitting /source endpoint

### ISSUE THREAD

**Issue by sky-eduardolopes** [rokudev/automated-channel-testing#2]
Able to create session and launch app. All interactions with app content are not working for me. Any idea on how I should debug this? Thank you

**Comment by rburdick100** [comment]
Can you provide some additional details regarding the operations that aren't working?  Do the test scripts work for you in conjunction with the sample channels?

**Comment by sky-eduardolopes** [comment]
I tried the Robot basic test script and it couldn't find elements and returned an invalid player state.
element, elements and element/active endpoints return 500. I suppose that's due to the fact that page source is empty.

**Comment by rburdick100** [comment]
The basic test script should work out of the box for you.  As is, it works with the RobotLibrary/channel.zip sample channel.  It could be modified for other purposes though.

As for the source endpoint, there is a binding only in the Robot webDriver version.  There isn't a keyword that exposes that to scripts (which would be easy to add) as we expected most people to look for elements, not the whole screen.

**Comment by sky-eduardolopes** [comment]
Doesn't the element endpoint use the same "endpointsMap["appUI"]" in the ecpClient? 

What I meant is none of the endpoints that are supposed to read the app content are working in my case.

 In my laptop I have other go projects and maybe that affected something in the build process. I'll try building in a cleaner machine. Do you guys advise a specific version of go? 

Would it be possible for you to release a built version of the driver? For MacOs?

**Comment by sky-eduardolopes** [comment]
Tried building in a machine with a fresh installation of go but result was the same.Is there any logging for the working parts so that I can try to understand where the communication is failing?

**Comment by sky-eduardolopes** [comment]
Had a call with developers. Problem was the firmware version of my Roku boxes, they are in 9.0.3 and the method created to read the appUI was only implemented in 9.1. Was able to run the tests in a box with 9.1 firmware
